### ISSUE TITLE
Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by sy-records** [waruqi/docsify-plugin-carbon#4]
![image](https://user-images.githubusercontent.com/33931153/107301748-0c214b00-6ab7-11eb-82e7-603867ffbcb4.png)
![image](https://user-images.githubusercontent.com/33931153/107301755-104d6880-6ab7-11eb-86de-192752e52812.png)

**Comment by sy-records** [comment]
This error occurs when clicking on the sidebar toggle

**Comment by waruqi** [comment]
This is caused by the latest patch, see https://github.com/waruqi/docsify-plugin-carbon/pull/2

@jhildenbiddle Can you help me to look at it?

**Comment by waruqi** [comment]
@sy-records What is your chrome version? I can't reproduce this problem here on my chrome.

**Comment by sy-records** [comment]
yeah, see https://docsify-preview-git-fork-sy-records-carbon.docsify-core.now.sh

**Comment by waruqi** [comment]
> https://docsify-preview-git-fork-sy-records-carbon.docsify-core.now.sh

It works for me.

![image](https://user-images.githubusercontent.com/151335/107303847-ded69c00-6aba-11eb-926e-7d89e054ac68.png)

**Comment by sy-records** [comment]
This error occurs when clicking on the sidebar toggle

**Comment by waruqi** [comment]
I have fixed it. v1.0.5

**Comment by jhildenbiddle** [comment]
@waruqi @sy-records 

Yep. I will fix this tonight. Looking forward to dropping IE11 support in docsify v5. :)

**Comment by jhildenbiddle** [comment]
@waruqi -- The "fix" your provided isn't a fix. It avoids the issue in modern browsers, but the issue remains in legacy browsers. See notes in #5 for details.

**Comment by waruqi** [comment]
> @waruqi -- The "fix" your provided isn't a fix. It avoids the issue in modern browsers, but the issue remains in legacy browsers. See notes in #5 for details.

Ok, thanks, I have merged this patch.

**Comment by waruqi** [comment]
@sy-records Can you try it again? 

BTW, How should I update the cdn cache? https://cdn.jsdelivr.net/npm/docsify-plugin-carbon@1/index.min.js @jhildenbiddle @sy-records

**Comment by sy-records** [comment]
Can only wait for jsdelivr to refresh automatically...

**Comment by jhildenbiddle** [comment]
@waruqi --

CDN has updated. You can close this issue.

https://cdn.jsdelivr.net/npm/docsify-plugin-carbon@1/index.js

Thanks!
